GAMES = [
    "Cyberpunk 2077",
    "The Witcher 3: Wild Hunt",
    "Fortnite",
    "Call of Duty: Warzone",
    "Minecraft",
    "Among Us",
    "Valorant",
    "Apex Legends",
    "Grand Theft Auto V",
    "FIFA 24",
    "League of Legends",
    "Counter-Strike: Global Offensive",
    "Overwatch",
    "Dota 2",
    "Rainbow Six Siege",
    "Rocket League",
    "Halo Infinite",
    "Assassin's Creed Valhalla",
    "Red Dead Redemption 2",
    "Super Smash Bros. Ultimate",
    "Animal Crossing: New Horizons",
    "Genshin Impact",
    "The Legend of Zelda: Breath of the Wild",
    "Pokémon Sword and Shield",
    "Monster Hunter Rise",
    "Death Stranding",
    "Marvel's Spider-Man: Miles Morales",
    "Resident Evil Village",
    "The Elder Scrolls V: Skyrim",
    "Ghost of Tsushima",
    "The Last of Us Part II",
    "God of War (2018)",
    "Dark Souls III",
    "Persona 5",
    "Bloodborne",
    "Uncharted 4: A Thief's End",
    "Horizon Zero Dawn",
    "Final Fantasy VII Remake",
    "DOOM Eternal",
    "Mortal Kombat 11",
    "Sekiro: Shadows Die Twice",
    "The Elder Scrolls Online",
    "NieR: Automata",
    "Deathloop",
    "Demon's Souls (2020)",
    "Baldur's Gate III",
    "Star Wars Jedi: Fallen Order",
    "Disco Elysium",
    "Control",
    "The Outer Worlds",
    "Borderlands 3",
    "DOOM (2016)",
    "The Sims 4",
    "Stardew Valley",
    "Terraria",
    "Factorio",
    "RimWorld",
    "Civilization VI",
    "Age of Empires IV",
    "Microsoft Flight Simulator",
    "Subnautica",
    "No Man's Sky",
    "Cities: Skylines",
    "Fallout 4",
    "The Division 2",
    "Tom Clancy's Rainbow Six: Extraction",
    "Forza Horizon 5",
    "F1 2023",
    "NBA 2K24",
    "Madden NFL 24",
    "WWE 2K24",
    "EA Sports UFC 5",
    "NHL 25",
    "PGA Tour 2K24",
    "Crash Bandicoot 4: It's About Time",
    "Tony Hawk's Pro Skater 1 + 2",
    "Resident Evil 3 (2020)",
    "Call of Duty: Black Ops Cold War",
    "Battlefield 2042",
    "Hades",
    "The Legend of Zelda: Skyward Sword HD",
    "Super Mario Odyssey",
    "Mario Kart 8 Deluxe",
    "The Legend of Zelda: Link's Awakening (2019)",
    "Super Mario 3D World + Bowser's Fury",
    "Animal Crossing: New Leaf",
    "Luigi's Mansion 3",
    "Super Mario Maker 2",
    "Fire Emblem: Three Houses",
    "Ring Fit Adventure",
    "Pokémon Brilliant Diamond and Shining Pearl",
    "Pokémon Legends: Arceus",
    "Monster Hunter Stories 2: Wings of Ruin",
    "Splatoon 2",
    "Xenoblade Chronicles: Definitive Edition",
    "Bravely Default II",
    "Octopath Traveler",
    "Fire Emblem Heroes",
    "Super Smash Bros. for Wii U",
    "Bayonetta 2",
    "Donkey Kong Country: Tropical Freeze",
    "ARMS",
    "Paper Mario: The Origami King",
    "Yoshi's Crafted World",
    "Pokémon Sword and Shield: Isle of Armor",
    "Pokémon Sword and Shield: Crown Tundra",
    "Kirby Star Allies",
    "Mario Tennis Aces",
    "Mario Golf: Super Rush",
    "New Super Mario Bros. U Deluxe",
    "The Legend of Zelda: Breath of the Wild - Expansion Pass",
    "Pikmin 3 Deluxe",
    "Hyrule Warriors: Age of Calamity",
    "Mario + Rabbids Kingdom Battle",
    "Captain Toad: Treasure Tracker",
    "Daemon X Machina",
    "Paper Mario: The Origami King",
    "Cuphead",
    "Hollow Knight",
    "Celeste",
    "Dead Cells",
    "Ori and the Blind Forest",
    "Shovel Knight",
    "Undertale",
    "Enter the Gungeon",
    "Hyper Light Drifter",
    "Stardew Valley",
    "Terraria",
    "Moonlighter",
    "Risk of Rain 2",
    "Slay the Spire",
    "Crypt of the NecroDancer",
    "Rogue Legacy",
    "Binding of Isaac: Rebirth",
    "Darkest Dungeon",
    "Spelunky 2",
    "Hollow Knight: Silksong",
    "Ori and the Will of the Wisps",
    "Cuphead: The Delicious Last Course",
    "Celeste: Farewell",
    "Dead Cells: Fatal Falls",
    "Stardew Valley: ConcernedApe's Untitled Project",
    "Divinity: Original Sin 2",
    "Pillars of Eternity II: Deadfire",
    "Wasteland 3",
    "Disco Elysium: The Final Cut",
    "Baldur's Gate: Enhanced Edition",
    "Planescape: Torment - Enhanced Edition",
    "Icewind Dale: Enhanced Edition",
    "Torment: Tides of Numenera",
    "Pathfinder: Kingmaker",
    "Pillars of Eternity",
    "Disco Elysium: The Final Cut",
    "Undertale",
    "Hollow Knight",
    "Celeste",
    "Dead Cells",
    "Ori and the Blind Forest",
    "Shovel Knight",
    "Stardew Valley",
    "Terraria",
    "Risk of Rain 2",
    "Slay the Spire",
    "Crypt of the NecroDancer",
    "Rogue Legacy",
    "Binding of Isaac: Rebirth",
    "Darkest Dungeon",
    "Spelunky 2",
    "Hades",
    "Ori and the Will of the Wisps",
    "Hollow Knight: Silksong",
    "Cuphead",
    "Celeste: Farewell",
    "Dead Cells: Fatal Falls",
    "Stardew Valley: ConcernedApe's Untitled Project",
    "The Legend of Zelda: Ocarina of Time",
    "The Legend of Zelda: Majora's Mask",
    "The Legend of Zelda: The Wind Waker",
    "The Legend of Zelda: Twilight Princess",
    "The Legend of Zelda: Skyward Sword",
    "The Legend of Zelda: A Link to the Past",
    "The Legend of Zelda: A Link Between Worlds",
    "The Legend of Zelda: Phantom Hourglass",
    "The Legend of Zelda: Spirit Tracks",
    "The Legend of Zelda: The Minish Cap",
    "The Legend of Zelda: Four Swords Adventures",
    "The Legend of Zelda: Four Swords",
    "The Legend of Zelda: Link's Awakening",
    "The Legend of Zelda: Oracle of Seasons",
    "The Legend of Zelda: Oracle of Ages",
    "The Legend of Zelda: Breath of the Wild",
    "The Legend of Zelda: Tri Force Heroes",
    "The Legend of Zelda: Hyrule Warriors",
    "The Legend of Zelda: Cadence of Hyrule",
    "The Legend of Zelda: Age of Calamity",
    "The Legend of Zelda: Breath of the Wild 2",
    "The Legend of Zelda: Tingle's Rosy Rupeeland",
    "The Legend of Zelda: Freshly-Picked Tingle's Rosy Rupeeland",
    "The Legend of Zelda: Wand of Gamelon",
    "The Legend of Zelda: Zelda's Adventure",
    "The Legend of Zelda: Link: The Faces of Evil",
    "The Legend of Zelda: Link's Crossbow Training",
    "The Legend of Zelda: Twilight Princess HD",
    "The Legend of Zelda: Wind Waker HD",
    "The Legend of Zelda: Skyward Sword HD",
    "The Legend of Zelda: Breath of the Wild - Expansion Pass",
    "The Legend of Zelda: Link's Awakening (2019)",
    "The Legend of Zelda: Majora's Mask 3D",
    "The Legend of Zelda: Ocarina of Time 3D",
    "The Legend of Zelda: Tri Force Heroes",
    "The Legend of Zelda: A Link Between Worlds",
    "The Legend of Zelda: Hyrule Warriors Legends",
    "The Legend of Zelda: Phantom Hourglass",
    "The Legend of Zelda: Spirit Tracks",
    "The Legend of Zelda: A Link to the Past & Four Swords",
    "The Legend of Zelda: Twilight Princess",
    "The Legend of Zelda: Phantom Hourglass",
    "The Legend of Zelda: Spirit Tracks",
    "The Legend of Zelda: Skyward Sword",
    "The Legend of Zelda: A Link Between Worlds",
    "The Legend of Zelda: Tri Force Heroes",
    "The Legend of Zelda: Breath of the Wild - Expansion Pass",
    "The Legend of Zelda: Link's Awakening (2019)",
    "Genshin Impact",
    "Honkai Impact 3rd",
    "Arknights",
    "Fate/Grand Order",
    "Azur Lane",
    "Girls' Frontline",
    "Granblue Fantasy",
    "Puzzle & Dragons",
    "Epic Seven",
    "The Alchemist Code",
    "Fire Emblem Heroes",
    "Dragalia Lost",
    "Brave Frontier",
    "Final Fantasy Brave Exvius",
    "Summoners War",
    "Knights Chronicle",
    "King's Raid",
    "SINoALICE",
    "Lineage 2: Revolution",
    "Grand Summoners",
    "Langrisser",
    "Destiny Child",
    "Star Ocean: Anamnesis",
    "Blade & Soul Revolution",
    "Another Eden",
    "Tales of Erin",
    "Onmyoji",
    "Raid: Shadow Legends",
    "AFK Arena",
    "Tokyo Afterschool Summoners",
    "Genshin Impact",
    "Honkai Impact 3rd",
    "Arknights",
    "Fate/Grand Order",
    "Azur Lane",
    "Girls' Frontline",
    "Granblue Fantasy",
    "Puzzle & Dragons",
    "Epic Seven",
    "The Alchemist Code",
    "Fire Emblem Heroes",
    "Dragalia Lost",
    "Brave Frontier",
    "Final Fantasy Brave Exvius",
    "Summoners War",
    "Knights Chronicle",
    "King's Raid",
    "SINoALICE",
    "Lineage 2: Revolution",
    "Grand Summoners",
    "Langrisser",
    "Destiny Child",
    "Star Ocean: Anamnesis",
    "Blade & Soul Revolution",
    "Another Eden",
    "Tales of Erin",
    "Onmyoji",
    "Atelier Marie Plus: The Alchemist of Salburg",
    "Atelier Elie GB",
    "Atelier Elkrone: Dear for Otomate",
    "Atelier Lise Plus: The Alchemist of Orde",
    "Atelier Marie & Elie: The Alchemists of Salburg 1-2",
    "Atelier Marie, Elie & Anis: Message on the Gentle Breeze",
    "Atelier Marie: The Alchemist of Salburg GB",
    "Atelier Judie: Gramnad no Renkinjutsushi",
    "Atelier Viorate: Gramnad no Renkinjutsushi 2",
    "Atelier Elie GB",
    "Atelier Lilie Plus: Alchemist of Salburg 3",
    "Atelier Iris: Eternal Mana 2",
    "Atelier Rorona: The Alchemist of Arland DX",
    "Atelier Totori: The Adventurer of Arland DX",
    "Atelier Meruru: The Apprentice of Arland DX",
    "Atelier Ayesha: The Alchemist of Dusk DX",
    "Atelier Escha & Logy: Alchemists of the Dusk Sky DX",
    "Atelier Shallie: Alchemists of the Dusk Sea DX",
    "Atelier Lulua: The Scion of Arland DX",
    "Atelier Ryza: Ever Darkness & the Secret Hideout DX",
    "Atelier Ryza 2: Lost Legends & the Secret Fairy DX",
    "Atelier Firis: The Alchemist and the Mysterious Journey DX",
    "Atelier Lydie & Suelle: The Alchemists and the Mysterious Paintings DX",
    "Atelier Sophie: The Alchemist of the Mysterious Book DX",
    "Atelier Marie & Elie: Zarlburg Alchemist",
    "Atelier Questboard",
    "Atelier Online: Alchemist of Bressisle",
    "Atelier Online: Bureseiru no Renkinjutsushi",
    "Atelier Online: Freyja no Atelier - Tasogare no Renkinjutsushi",
    "Atelier Online: Alchemist of Bressisle",
    "Resident Evil 7: Biohazard",
    "Resident Evil Village",
    "Resident Evil 3 (2020)",
    "Resident Evil 2 (2019)",
    "Resident Evil: Revelations 2",
    "Resident Evil: Revelations",
    "Resident Evil: Operation Raccoon City",
    "Resident Evil: The Darkside Chronicles",
    "Resident Evil: The Umbrella Chronicles",
    "Resident Evil: Dead Aim",
    "Resident Evil Survivor",
    "Resident Evil Survivor 2 – Code: Veronica",
    "Resident Evil: Gaiden",
    "Resident Evil: The Mercenaries 3D",
    "Resident Evil: The Missions",
    "Resident Evil: The Stories",
    "Resident Evil: The Deck Building Game",
    "Resident Evil Outbreak",
    "Resident Evil Outbreak File #2",
    "Resident Evil: Genesis",
    "Resident Evil: Deadly Silence",
    "Resident Evil: Degeneration",
    "Resident Evil: Confidential Report",
    "Resident Evil: Confidential Report 2",
    "Resident Evil: The Umbrella Chronicles (Wii Zapper bundle)",
    "Resident Evil: The Darkside Chronicles (Wii Zapper bundle)",
    "Resident Evil (1996)",
    "Resident Evil 2 (1998)",
    "Resident Evil 3: Nemesis (1999)",
    "Resident Evil Survivor 2 Code: Veronica",
    "Danganronpa V3: Killing Harmony",
    "Danganronpa 1-2 Reload",
    "Danganronpa Another Episode: Ultra Despair Girls",
    "Danganronpa Trilogy",
    "Danganronpa S: Ultimate Summer Camp",
    "Danganronpa: Trigger Happy Havoc",
    "Danganronpa 2: Goodbye Despair",
    "Danganronpa: Unlimited Battle",
    "Danganronpa: The Animation",
    "Danganronpa 3: The End of Hope's Peak High School - Future Arc",
    "Danganronpa 3: The End of Hope's Peak High School - Despair Arc",
    "Danganronpa 3: The End of Hope's Peak High School - Hope Arc",
    "Danganronpa: The Stage",
    "Danganronpa: Monokuma Strikes Back",
    "Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei The Animation",
    "Danganronpa 2.5: Nagito Komaeda and the Destroyer of the World",
    "Danganronpa Another Episode: Ultra Despair Girls - Komaru Naegi's 7 Days of Despair",
    "Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei",
    "Danganronpa: Kibou no Gakuen to Zetsubou no Koukousei THE STAGE 2016",
    "Danganronpa: Trigger Happy Havoc IF",
    "Danganronpa: The Animation - The Four Dark Devas of Destruction",
    "Danganronpa: The Animation - Despair Arc",
    "Danganronpa: The Animation - Future Arc",
    "Danganronpa 3: The End of Kibougamine Gakuen",
    "Danganronpa 3: The End of Kibougamine Gakuen - Kibou-hen",
    "Danganronpa: Another Episode",
    "Danganronpa 1.2 Reload",
    "Danganronpa 1.2",
    "Danganronpa 3: The End of Kibougamine Gakuen - Mirai-hen",
    "Danganronpa 3: The End of Kibougamine Gakuen - Zetsubou-hen",
    "Grand Theft Auto: Chinatown Wars",
    "Grand Theft Auto Advance",
    "Grand Theft Auto: Liberty City Stories",
    "Grand Theft Auto: Vice City Stories",
    "Grand Theft Auto: San Andreas",
    "Grand Theft Auto: Vice City",
    "Grand Theft Auto III",
    "Grand Theft Auto 2",
    "Grand Theft Auto",
    "Grand Theft Auto: London 1961",
    "Grand Theft Auto: London 1969",
    "Grand Theft Auto IV: The Lost and Damned",
    "Grand Theft Auto IV: The Ballad of Gay Tony",
    "Grand Theft Auto V: Online",
    "Grand Theft Auto: London, 1969",
    "Grand Theft Auto: San Andreas Stories",
    "Grand Theft Auto: Tokyo",
    "Grand Theft Auto: Bogota",
    "Grand Theft Auto: Berlin",
    "Grand Theft Auto: Carcer City",
    "Grand Theft Auto: Sin City",
    "Grand Theft Auto: Tokyo 2020",
    "Grand Theft Auto: Tokyo Drift",
    "Grand Theft Auto: London 3D",
    "Grand Theft Auto: Bogota",
    "Grand Theft Auto: Sin City",
    "Grand Theft Auto: Tokyo",
    "Grand Theft Auto: Amsterdam",
    "Grand Theft Auto: Tokyo Drift",
    "Grand Theft Auto: Mexico City",
    "Phoenix Wright: Ace Attorney",
    "Phoenix Wright: Ace Attorney - Justice for All",
    "Phoenix Wright: Ace Attorney - Trials and Tribulations",
    "Apollo Justice: Ace Attorney",
    "Ace Attorney Investigations: Miles Edgeworth",
    "Ace Attorney Investigations 2",
    "Phoenix Wright: Ace Attorney Trilogy",
    "The Great Ace Attorney Chronicles",
    "The Great Ace Attorney: Adventures",
    "The Great Ace Attorney 2: Resolve",
    "The Great Ace Attorney Chronicles",
    "Phoenix Wright: Ace Attorney - Dual Destinies",
    "Phoenix Wright: Ace Attorney - Spirit of Justice",
    "The Great Ace Attorney Chronicles",
    "Professor Layton vs. Phoenix Wright: Ace Attorney",
    "The Great Ace Attorney: The Adventures of Ryūnosuke Naruhodō",
    "The Great Ace Attorney 2: The Resolve of Ryūnosuke Naruhodō",
    "The Great Ace Attorney: Chronicles",
    "Phoenix Wright: Ace Attorney Trilogy HD",
    "Phoenix Wright: Ace Attorney Trilogy",
    "Ace Attorney Investigations: Miles Edgeworth - Prosecutor's Path",
    "Dai Gyakuten Saiban 2: Naruhodou Ryuunosuke no Kakugo",
    "The Great Ace Attorney: The Resolve of Naruhodō Ryūnosuke",
    "Gyakuten Kenji",
    "Gyakuten Kenji 2",
    "Gyakuten Kenji: Jōdai Shinshutsu!",
    "Gyakuten Saiban",
    "Gyakuten Saiban 2",
    "Gyakuten Saiban 3",
    "Yakuza 6: The Song of Life",
    "Yakuza: Like a Dragon",
    "Yakuza Kiwami",
    "Yakuza Kiwami 2",
    "Yakuza 0",
    "Yakuza 3 Remastered",
    "Yakuza 4 Remastered",
    "Yakuza 5 Remastered",
    "Yakuza: Dead Souls",
    "Ryu ga Gotoku Kenzan!",
    "Ryu ga Gotoku Ishin!",
    "Ryu ga Gotoku Online",
    "Kurohyou: Ryu ga Gotoku Shinshou",
    "Kurohyou 2: Ryu ga Gotoku Ashura-hen",
    "Ryu ga Gotoku (PS2)",
    "Ryu ga Gotoku 2 (PS2)",
    "Ryu ga Gotoku Kenzan! (PS3)",
    "Ryu ga Gotoku 3 (PS3)",
    "Ryu ga Gotoku 4: Densetsu o Tsugumono (PS3)",
    "Ryu ga Gotoku: Kurohyou 2 (PSP)",
    "Ryu ga Gotoku 5: Yume, Kanaeshi Mono (PS3)",
    "Ryu ga Gotoku: Ashura-hen (PS3)",
    "Ryu ga Gotoku: Kizuna (PSP)",
    "Ryu ga Gotoku 1&2 HD Edition (PS3)",
    "Yakuza: Of the End (PS3)",
    "Ryu ga Gotoku 1&2 HD Edition (Wii U)",
    "Yakuza 0: The Business Card Machine (iOS)",
    "Yakuza: Like a Dragon - The Movie (iOS)",
    "Yakuza: Dead Souls (PS3)",
    "Yakuza: Kiwami 2 - The Grand Clan Creator (iOS)",
    "The Witcher 3: Wild Hunt",
    "Red Dead Redemption 2",
    "Final Fantasy VII Remake",
    "God of War (2018)",
    "Persona 5",
    "Bloodborne",
    "The Elder Scrolls V: Skyrim",
    "Dark Souls III",
    "Horizon Zero Dawn",
    "Uncharted 4: A Thief's End",
    "The Last of Us Part II",
    "Ghost of Tsushima",
    "Demon's Souls (2020)",
    "Marvel's Spider-Man",
    "NieR: Automata",
    "Mass Effect 2",
    "Mass Effect 3",
    "Metal Gear Solid V: The Phantom Pain",
    "Counter-Strike: Global Offensive",
    "Dota 2",
    "League of Legends",
    "Valorant",
    "Overwatch",
    "Rainbow Six Siege",
    "Call of Duty: Warzone",
    "PlayerUnknown's Battlegrounds",
    "Apex Legends",
    "Fortnite",
    "Genshin Impact",
    "Rocket League",
    "Destiny 2",
    "The Elder Scrolls Online",
    "Street Fighter V",
    "Super Smash Bros. Ultimate",
    "Tekken 7",
    "Mortal Kombat 11",
    "Guilty Gear Strive",
    "Soulcalibur VI",
    "Dead or Alive 6",
    "Dragon Ball FighterZ",
    "Power Rangers: Battle for the Grid",
    "Brawlhalla",
    "For Honor",
    "Nidhogg",
    "Nidhogg 2",
    "Absolver",
    "Samurai Shodown",
    "Killer Instinct",
    "Skullgirls",
    "BlazBlue: Cross Tag Battle",
    "Rivals of Aether",
    "Pokémon Sword and Shield",
    "Pokkén Tournament DX",
    "Mario Tennis Aces",
    "Splatoon 2",
    "ARMS",
    "StarCraft II",
    "Age of Empires II: Definitive Edition",
    "Warcraft III: Reforged",
    "Smite",
    "Heroes of the Storm",
    "Battlerite",
    "Paladins",
    "Dead by Daylight",
    "Friday the 13th: The Game",
    "Evolve",
    "World of Tanks",
    "World of Warships",
    "World of Warplanes",
    "Crossout",
    "War Thunder",
    "Armored Warfare",
    "Trove",
    "Guns of Icarus Online",
    "Albion Online",
    "Bless Unleashed",
    "Conqueror's Blade",
    "Black Desert Online",
    "EVE Online",
    "Final Fantasy XIV",
    "Guild Wars 2",
    "Neverwinter",
    "Path of Exile",
    "RuneScape",
    "The Elder Scrolls Online",
    "Tibia",
    "World of Warcraft",
    "Assassin's Creed",
    "Assassin's Creed II",
    "Assassin's Creed: Brotherhood",
    "Assassin's Creed: Revelations",
    "Assassin's Creed III",
    "Assassin's Creed IV: Black Flag",
    "Assassin's Creed Rogue",
    "Assassin's Creed Unity",
    "Assassin's Creed Syndicate",
    "Assassin's Creed Origins",
    "Assassin's Creed Odyssey",
    "Assassin's Creed Valhalla",
    "Tom Clancy's Rainbow Six",
    "Tom Clancy's Rainbow Six: Rogue Spear",
    "Tom Clancy's Rainbow Six 3: Raven Shield",
    "Tom Clancy's Rainbow Six: Vegas",
    "Tom Clancy's Rainbow Six: Vegas 2",
    "Tom Clancy's Rainbow Six: Siege",
    "Tom Clancy's Ghost Recon",
    "Tom Clancy's Ghost Recon: Desert Siege",
    "Tom Clancy's Ghost Recon: Island Thunder",
    "Tom Clancy's Ghost Recon 2",
    "Tom Clancy's Ghost Recon 2: Summit Strike",
    "Tom Clancy's Ghost Recon Advanced Warfighter",
    "Tom Clancy's Ghost Recon Advanced Warfighter 2",
    "Tom Clancy's Ghost Recon: Future Soldier",
    "Tom Clancy's Splinter Cell",
    "Tom Clancy's Splinter Cell: Pandora Tomorrow",
    "Tom Clancy's Splinter Cell: Chaos Theory",
    "Tom Clancy's Splinter Cell: Double Agent",
    "Tom Clancy's Splinter Cell: Conviction",
    "Tom Clancy's Splinter Cell: Blacklist",
    "Far Cry",
    "Far Cry 2",
    "Far Cry 3",
    "Far Cry 3: Blood Dragon",
    "Far Cry 4",
    "Far Cry Primal",
    "Far Cry 5",
    "Far Cry New Dawn",
    "Prince of Persia: The Sands of Time",
    "Prince of Persia: Warrior Within",
    "Prince of Persia: The Two Thrones",
    "Prince of Persia (2008)",
    "Prince of Persia: The Forgotten Sands",
    "Prince of Persia: The Sands of Time Remake",
    "Watch Dogs",
    "Watch Dogs 2",
    "Watch Dogs: Legion",
    "The Division",
    "The Division 2",
    "For Honor",
    "Steep",
    "The Crew",
    "The Crew 2",
    "Just Dance",
    "Rayman",
    "Rayman Raving Rabbids",
    "Rayman Legends",
    "Beyond Good & Evil",
    "Child of Light",
    "Valiant Hearts: The Great War",
    "Trials",
    "Trials Evolution",
    "Trials Fusion",
    "Trials Rising",
    "South Park: The Stick of Truth",
    "South Park: The Fractured but Whole",
    "Grow Home",
    "Grow Up",
    "Rocksmith",
    "Rocksmith 2014 Edition",
    "Anno",
    "Anno 1800",
    "Anno 2070",
    "Anno 2205",
    "Anno 1404",
    "Anno 1701",
    "Anno 1602",
    "Anno 1503",
    "FIFA",
    "Madden NFL",
    "NBA Live",
    "NHL",
    "UFC",
    "PGA Tour",
    "FIFA Street",
    "NCAA Football",
    "NASCAR",
    "SSX",
    "Skate",
    "Fight Night",
    "Def Jam",
    "EA Sports UFC",
    "NFL Street",
    "NBA Street",
    "NHL Hitz",
    "MVP Baseball",
    "The Sims",
    "SimCity",
    "Command & Conquer",
    "Mass Effect",
    "Dragon Age",
    "Need for Speed",
    "Burnout",
    "Medal of Honor",
    "Battlefield",
    "Titanfall",
    "Star Wars: Battlefront",
    "Dead Space",
    "Crysis",
    "Mirror's Edge",
    "Army of Two",
    "Dante's Inferno",
    "Plants vs. Zombies",
    "Peggle",
    "Bejeweled",
    "Apex Legends",
    "Anthem",
    "The Lord of the Rings",
    "Harry Potter",
    "The Godfather",
    "James Bond",
    "Sonic the Hedgehog",
    "The Simpsons",
    "SSX",
    "Burnout",
    "Dungeon Keeper",
    "Wing Commander",
    "Syndicate",
    "Ultima",
    "Populous",
    "Dead Space",
    "Spore",
    "Mercenaries",
    "Road Rash",
    "Theme Hospital",
    "Black & White",
    "Jade Empire",
    "Bulletstorm",
    "Brütal Legend",
    "Kingdoms of Amalur: Reckoning",
    "Mirror's Edge Catalyst",
    "Star Wars Jedi: Fallen Order",
    "A Way Out",
    "Unravel",
    "Unravel Two",
    "Fe",
    "Sea of Solitude",
    "Knockout City",
    "It Takes Two",
    "Lost in Random",
    "Rocket Arena",
    "Skate 4",
    "Gridiron Champions",
    "Shin Megami Tensei: Persona",
    "Persona 2: Innocent Sin",
    "Persona 2: Eternal Punishment",
    "Shin Megami Tensei: Persona 3",
    "Persona 3 FES",
    "Persona 3 Portable",
    "Persona 4",
    "Persona 4 Golden",
    "Persona 4 Arena",
    "Persona 4 Arena Ultimax",
    "Persona Q: Shadow of the Labyrinth",
    "Persona Q2: New Cinema Labyrinth",
    "Persona 5",
    "Persona 5 Royal",
    "Persona 5 Strikers",
    "Shin Megami Tensei: Persona 4",
    "Shin Megami Tensei: Persona 4 Golden",
    "Shin Megami Tensei: Persona 3 Portable",
    "Shin Megami Tensei: Persona 3 FES",
    "Shin Megami Tensei: Persona 2 - Innocent Sin",
    "Shin Megami Tensei: Persona 2 - Eternal Punishment",
    "Persona 4: Dancing All Night",
    "Persona 3: Dancing in Moonlight",
    "Persona 5: Dancing in Starlight",
    "Five Nights at Freddy's: Help Wanted Mobile",
    "Five Nights at Freddy's: Security Breach Mobile",
    "Five Nights at Freddy's: Help Wanted: Curse of Dreadbear",
    "Five Nights at Freddy's: Help Wanted: Parts & Service",
    "Five Nights at Freddy's: Help Wanted: Vent Repair",
    "Five Nights at Freddy's: Help Wanted: Night Terrors",
    "Five Nights at Freddy's: Security Breach: Deluxe Edition",
    "Five Nights at Freddy's: Into Madness",
    "Five Nights at Freddy's: Fazbear Frights",
    "Five Nights at Freddy's: Fazbear Frights 2: Fetch",
    "Five Nights at Freddy's: Fazbear Frights 3: 1:35 AM",
    "Five Nights at Freddy's: Fazbear Frights 4: Step Closer",
    "Five Nights at Freddy's: Fazbear Frights 5: Bunny Call",
    "Five Nights at Freddy's: Fazbear Frights 6: Blackbird",
    "Five Nights at Freddy's: Fazbear Frights 7: The Cliffs",
    "Five Nights at Freddy's: Fazbear Frights 8: Gumdrop Angel",
    "Five Nights at Freddy's: Fazbear Frights 9: The Puppet Carver",
    "Five Nights at Freddy's: Fazbear Frights 10: Friendly Face",
    "Five Nights at Freddy's: Fazbear Frights 11: Prankster",
    "Five Nights at Freddy's: Fazbear Frights 12: Free Roaming",
    "Five Nights at Freddy's: Fazbear Frights 13: Terrible Twos",
    "Five Nights at Freddy's: Fazbear Frights 14: What We Found",
    "Five Nights at Freddy's: Fazbear Frights 15: Trick or Treat",
    "Five Nights at Freddy's: Fazbear Frights 16: Dance with Me",
    "Five Nights at Freddy's: Fazbear Frights 17: The Puddle",
    "Five Nights at Freddy's: Fazbear Frights 18: Blackout",
    "Five Nights at Freddy's: Fazbear Frights 19: Hide and Seek",
    "Five Nights at Freddy's: Fazbear Frights 20: Welcome to the Show",
    "Five Nights at Freddy's: Fazbear Frights 21: Fazbear Frights: Ball Pit",
    "Five Nights at Freddy's: Fazbear Frights 22: Fazbear Frights: Freezing",
    "Five Nights at Freddy's: Fazbear Frights 23: Fazbear Frights: Reckoning",
    "Spider-Man (2000)",
    "Spider-Man 2: Enter Electro",
    "Spider-Man: Mysterio's Menace",
    "Spider-Man: The Movie",
    "Spider-Man 2 (2004)",
    "Ultimate Spider-Man",
    "Spider-Man 3 (2007)",
    "Spider-Man: Friend or Foe",
    "Spider-Man: Web of Shadows",
    "Spider-Man: Shattered Dimensions",
    "Spider-Man: Edge of Time",
    "The Amazing Spider-Man (2012)",
    "The Amazing Spider-Man 2 (2014)",
    "Spider-Man Unlimited",
    "Spider-Man (2018)",
    "Marvel's Spider-Man: Miles Morales",
    "Spider-Man: Battle for New York",
    "Spider-Man: Toxic City",
    "Spider-Man: Total Mayhem",
    "Spider-Man: Ultimate Power",
]
